<a href="https://colab.research.google.com/github/jadaksnyder/Artificial-Intelligence/blob/main/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import torch

#this creates a 1D tensor
a = torch.tensor([1, 2, 3, 4, 5])
print(a)

#this creates a 2D tensor
b = torch.tensor([[1,2,3], [4,5,6]])
print(b)



tensor([1, 2, 3, 4, 5])
tensor([[1, 2, 3],
        [4, 5, 6]])


In [15]:
import torch
#creating the 2D tensor of shape (3,3) with random values
tensor = torch.rand(3,3)
print(tensor)

#find the shape, data type, and device of tensor
print("Shape of the tensor: ", tensor.shape)
print("Data type of tensor: ", tensor.dtype)
print("Device of tensor: ", tensor.device)

#perform element-wise addition and multiplication

#create another tensor for addition (Note to self: must be same shape.)
tensor2 = torch.rand(3,3)

#use torch.add to add the two tensors
result_add = torch.add(tensor, tensor2)
print("Result: ", result_add)

#use torch.mul to multiply the two tensors
result_mul = torch.mul(tensor, tensor2)
print("Result: ", result_mul)



tensor([[0.3140, 0.9245, 0.1050],
        [0.1004, 0.4958, 0.1764],
        [0.7634, 0.0774, 0.6525]])
Shape of the tensor:  torch.Size([3, 3])
Data type of tensor:  torch.float32
Device of tensor:  cpu
Result:  tensor([[1.1249, 1.3581, 0.7932],
        [1.0605, 1.4194, 1.1242],
        [1.5772, 0.9117, 0.9344]])
Result:  tensor([[0.2546, 0.4009, 0.0723],
        [0.0964, 0.4580, 0.1672],
        [0.6213, 0.0646, 0.1839]])
